### ISSUE TITLE
TTGO T-Beam v1.0 ESP32 LoRa 433MHz

### ISSUE THREAD

**Issue by OM8AKX** [lora-aprs/TTGO-T-Beam_GPS-reset#1]
I try this code on my board but it still stops at the STATE 0 level and doesn't continue even after a few hours. 

![reset](https://user-images.githubusercontent.com/19824829/106389130-26d23080-63e2-11eb-9e52-ca28f744a4e4.jpg)

**Comment by peterus** [comment]
do you still have this issue? i just checked the code and it looks like the serial connection could be brocken on your board.
