### ISSUE TITLE
Binary File

### ISSUE THREAD

**Issue by catalinalb** [lora-aprs/TTGO-T-Beam_GPS-reset#2]
Hello,

Can you add a binary file that could be easily flashed ?

I am new to Virtual Studio COde, though my board is located at COM7 but the VS Code tries to flash it at COM14 and I did not find where to change that. 
So I went in src folder and opened the ino file in Arduino, installed the SparkFunk ublox library, disabled the version that I don´t need ( 0.7 ) but still I got the following issue:

C:\Users\catal\Downloads\TTGO-T-Beam_GPS-reset-main\TTGO-T-Beam_GPS-reset-main\src\T22-GPS-restoreFactory-v2\T22-GPS-restoreFactory-v2.ino: In function 'void setup()':
T22-GPS-restoreFactory-v2:75:36: error: 'GPS_RX_PIN' was not declared in this scope
  SerialGPS.begin(9600, SERIAL_8N1, GPS_RX_PIN, GPS_TX_PIN);
                                    ^
T22-GPS-restoreFactory-v2:75:48: error: 'GPS_TX_PIN' was not declared in this scope
  SerialGPS.begin(9600, SERIAL_8N1, GPS_RX_PIN, GPS_TX_PIN);
                                                ^
C:\Users\catal\Downloads\TTGO-T-Beam_GPS-reset-main\TTGO-T-Beam_GPS-reset-main\src\T22-GPS-restoreFactory-v2\T22-GPS-restoreFactory-v2.ino: In function 'void loop()':
T22-GPS-restoreFactory-v2:116:37: error: 'GPS_RX_PIN' was not declared in this scope
   SerialGPS.begin(9600, SERIAL_8N1, GPS_RX_PIN, GPS_TX_PIN);
                                     ^
T22-GPS-restoreFactory-v2:116:49: error: 'GPS_TX_PIN' was not declared in this scope
   SerialGPS.begin(9600, SERIAL_8N1, GPS_RX_PIN, GPS_TX_PIN);
                                                 ^
exit status 1
'GPS_RX_PIN' was not declared in this scope

Thank you,
Catalin

**Comment by peterus** [comment]
It will not make very much sense to create a release process and add the binaries for this small project.

But I can help with this issue ;) you can force platformio to use a special port for upload and monitor. Add this into your platformio.ini file in the `[env]` section:
```
upload_port = COM7
monitor_port = COM7
```

so it should look like this:
```
[env]
platform = espressif32 @ 3.0.0
framework = arduino
board = ttgo-t-beam
lib_ldf_mode = deep+
monitor_speed = 115200
check_tool = cppcheck
check_flags =
    cppcheck: --suppress=*:*.pio\* --inline-suppr

upload_port = COM7
monitor_port = COM7

#ESP8266 and ESP32 OLED driver for SSD1306 displays
[env:ttgo-t-beam-v1]
lib_deps = 
	SparkFun u-blox Arduino Library
	AXP202X_Library
build_flags = -DT_BEAM_V10

[env:ttgo-t-beam-v0_7]
lib_deps = SparkFun u-blox Arduino Library
build_flags = -DT_BEAM_V07
```
